### ISSUE TITLE
Future features/to-do #1

### ISSUE THREAD

**Issue by TheMajorTechie** [TheMajorTechie/Charatrack#3]
- [ ] Tabs within the Charatrack window to allow easier switching between characters
- [ ] Allow user to look into the character's "past" by allowing saves to be tied to a specific label or in-story date
- [ ] Per-story characters/story selector on startup

To do:
- [ ] Clean up the discrepancy between memory and knowledge in the code. Likely will be sticking with "Character's memories" to better clarify the intention of the panel.
